/**
 * Local NSE stock search utility.
 * All NIFTY 500 stocks embedded for instant client-side search.
 */

export interface NseStock {
  symbol: string;
  name: string;
  sector?: string;
}

/**
 * Complete NIFTY 500 stock list for instant search.
 * Source: apps/api/data/nifty500_seed.json
 */
const NIFTY_500: NseStock[] = [
  { symbol: "360ONE", name: "360 One Wam Limited", sector: "Stockbroking & Allied" },
  { symbol: "3MINDIA", name: "3M India Limited", sector: "Diversified" },
  { symbol: "AADHARHFC", name: "Aadhar Housing Finance Limited", sector: "Housing Finance Company" },
  { symbol: "AARTIIND", name: "Aarti Industries Limited", sector: "Specialty Chemicals" },
  { symbol: "AAVAS", name: "Aavas Financiers Limited", sector: "Housing Finance Company" },
  { symbol: "ABB", name: "Abb India Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "ABBOTINDIA", name: "Abbott India Limited", sector: "Pharmaceuticals" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital Limited", sector: "Investment Company" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion And Retail Limited", sector: "Speciality Retail" },
  { symbol: "ABLBL", name: "Aditya Birla Lifestyle Brands Limited", sector: "Speciality Retail" },
  { symbol: "ABREL", name: "Aditya Birla Real Estate Limited", sector: "Paper & Paper Products" },
  { symbol: "ABSLAMC", name: "Aditya Birla Sun Life Amc Limited", sector: "Asset Management Company" },
  { symbol: "ACC", name: "Acc Limited", sector: "Cement & Cement Products" },
  { symbol: "ACE", name: "Action Construction Equipment Limited", sector: "Construction Vehicles" },
  { symbol: "ACMESOLAR", name: "Acme Solar Holdings Limited", sector: "Power Generation" },
  { symbol: "ADANIENSOL", name: "Adani Energy Solutions Limited", sector: "Power Distribution" },
  { symbol: "ADANIENT", name: "Adani Enterprises Limited", sector: "Trading - Minerals" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy Limited", sector: "Power Generation" },
  { symbol: "ADANIPORTS", name: "Adani Ports And Special Economic Zone Limited", sector: "Port & Port services" },
  { symbol: "ADANIPOWER", name: "Adani Power Limited", sector: "Integrated Power Utilities" },
  { symbol: "AEGISLOG", name: "Aegis Logistics Limited", sector: "Trading - Gas" },
  { symbol: "AEGISVOPAK", name: "Aegis Vopak Terminals Limited", sector: "Oil Storage & Transportation" },
  { symbol: "AFCONS", name: "Afcons Infrastructure Limited", sector: "Civil Construction" },
  { symbol: "AFFLE", name: "Affle 3I Limited", sector: "IT Enabled Services" },
  { symbol: "AGARWALEYE", name: "Dr. Agarwal'S Health Care Limited", sector: "Hospital" },
  { symbol: "AIAENG", name: "Aia Engineering Limited", sector: "Castings & Forgings" },
  { symbol: "AIIL", name: "Authum Investment & Infrastructure Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "AJANTPHARM", name: "Ajanta Pharma Limited", sector: "Pharmaceuticals" },
  { symbol: "AKUMS", name: "Akums Drugs And Pharmaceuticals Limited", sector: "Pharmaceuticals" },
  { symbol: "AKZOINDIA", name: "Akzo Nobel India Limited", sector: "Paints" },
  { symbol: "ALKEM", name: "Alkem Laboratories Limited", sector: "Pharmaceuticals" },
  { symbol: "ALKYLAMINE", name: "Alkyl Amines Chemicals Limited", sector: "Specialty Chemicals" },
  { symbol: "ALOKINDS", name: "Alok Industries Limited", sector: "Other Textile Products" },
  { symbol: "AMBER", name: "Amber Enterprises India Limited", sector: "Household Appliances" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Limited", sector: "Cement & Cement Products" },
  { symbol: "ANANDRATHI", name: "Anand Rathi Wealth Limited", sector: "Financial Products Distributor" },
  { symbol: "ANANTRAJ", name: "Anant Raj Limited", sector: "Residential Commercial Projects" },
  { symbol: "ANGELONE", name: "Angel One Limited", sector: "Stockbroking & Allied" },
  { symbol: "APARINDS", name: "Apar Industries Limited", sector: "Other Electrical Equipment" },
  { symbol: "APLAPOLLO", name: "Apl Apollo Tubes Limited", sector: "Iron & Steel Products" },
  { symbol: "APLLTD", name: "Alembic Pharmaceuticals Limited", sector: "Pharmaceuticals" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise Limited", sector: "Hospital" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres Limited", sector: "Tyres & Rubber Products" },
  { symbol: "APTUS", name: "Aptus Value Housing Finance India Limited", sector: "Housing Finance Company" },
  { symbol: "ARE&M", name: "Amara Raja Energy & Mobility Limited", sector: "Auto Components & Equipments" },
  { symbol: "ASAHIINDIA", name: "Asahi India Glass Limited", sector: "Auto Components & Equipments" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland Limited", sector: "Commercial Vehicles" },
  { symbol: "ASIANPAINT", name: "Asian Paints Limited", sector: "Paints" },
  { symbol: "ASTERDM", name: "Aster Dm Healthcare Limited", sector: "Hospital" },
  { symbol: "ASTRAL", name: "Astral Limited", sector: "Plastic Products - Industrial" },
  { symbol: "ASTRAZEN", name: "Astrazeneca Pharma India Limited", sector: "Pharmaceuticals" },
  { symbol: "ATGL", name: "Adani Total Gas Limited", sector: "LPG/CNG/PNG/LNG Supplier" },
  { symbol: "ATHERENERG", name: "Ather Energy Limited", sector: "2/3 Wheelers" },
  { symbol: "ATUL", name: "Atul Limited", sector: "Specialty Chemicals" },
  { symbol: "AUBANK", name: "Au Small Finance Bank Limited", sector: "Other Bank" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma Limited", sector: "Pharmaceuticals" },
  { symbol: "AWL", name: "Awl Agri Business Limited", sector: "Edible Oil" },
  { symbol: "AXISBANK", name: "Axis Bank Limited", sector: "Private Sector Bank" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Limited", sector: "2/3 Wheelers" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv Limited", sector: "Holding Company" },
  { symbol: "BAJAJHFL", name: "Bajaj Housing Finance Limited", sector: "Housing Finance Company" },
  { symbol: "BAJAJHLDNG", name: "Bajaj Holdings & Investment Limited", sector: "Holding Company" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries Limited", sector: "Tyres & Rubber Products" },
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills Limited", sector: "Sugar" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank Limited", sector: "Private Sector Bank" },
  { symbol: "BANKBARODA", name: "Bank Of Baroda", sector: "Public Sector Bank" },
  { symbol: "BANKINDIA", name: "Bank Of India", sector: "Public Sector Bank" },
  { symbol: "BASF", name: "Basf India Limited", sector: "Specialty Chemicals" },
  { symbol: "BATAINDIA", name: "Bata India Limited", sector: "Footwear" },
  { symbol: "BAYERCROP", name: "Bayer Cropscience Limited", sector: "Pesticides & Agrochemicals" },
  { symbol: "BBTC", name: "The Bombay Burmah Trading Corporation Limited", sector: "Packaged Foods" },
  { symbol: "BDL", name: "Bharat Dynamics Limited", sector: "Aerospace & Defense" },
  { symbol: "BEL", name: "Bharat Electronics Limited", sector: "Aerospace & Defense" },
  { symbol: "BEML", name: "Beml Limited", sector: "Construction Vehicles" },
  { symbol: "BERGEPAINT", name: "Berger Paints (I) Limited", sector: "Paints" },
  { symbol: "BHARATFORG", name: "Bharat Forge Limited", sector: "Auto Components & Equipments" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel Limited", sector: "Telecom - Cellular & Fixed line services" },
  { symbol: "BHARTIHEXA", name: "Bharti Hexacom Limited", sector: "Telecom - Cellular & Fixed line services" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "BIKAJI", name: "Bikaji Foods International Limited", sector: "Packaged Foods" },
  { symbol: "BIOCON", name: "Biocon Limited", sector: "Pharmaceuticals" },
  { symbol: "BLS", name: "Bls International Services Limited", sector: "Tour Travel Related Services" },
  { symbol: "BLUEDART", name: "Blue Dart Express Limited", sector: "Logistics Solution Provider" },
  { symbol: "BLUEJET", name: "Blue Jet Healthcare Limited", sector: "Pharmaceuticals" },
  { symbol: "BLUESTARCO", name: "Blue Star Limited", sector: "Household Appliances" },
  { symbol: "BOSCHLTD", name: "Bosch Limited", sector: "Auto Components & Equipments" },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation Limited", sector: "Refineries & Marketing" },
  { symbol: "BRIGADE", name: "Brigade Enterprises Limited", sector: "Residential Commercial Projects" },
  { symbol: "BRITANNIA", name: "Britannia Industries Limited", sector: "Packaged Foods" },
  { symbol: "BSE", name: "Bse Limited", sector: "Exchange and Data Platform" },
  { symbol: "BSOFT", name: "Birlasoft Limited", sector: "Computers - Software & Consulting" },
  { symbol: "CAMPUS", name: "Campus Activewear Limited", sector: "Footwear" },
  { symbol: "CAMS", name: "Computer Age Management Services Limited", sector: "Depositories Clearing Houses and Other Intermediaries" },
  { symbol: "CANBK", name: "Canara Bank", sector: "Public Sector Bank" },
  { symbol: "CANFINHOME", name: "Can Fin Homes Limited", sector: "Housing Finance Company" },
  { symbol: "CAPLIPOINT", name: "Caplin Point Laboratories Limited", sector: "Pharmaceuticals" },
  { symbol: "CARBORUNIV", name: "Carborundum Universal Limited", sector: "Abrasives & Bearings" },
  { symbol: "CASTROLIND", name: "Castrol India Limited", sector: "Lubricants" },
  { symbol: "CCL", name: "Ccl Products (India) Limited", sector: "Tea & Coffee" },
  { symbol: "CDSL", name: "Central Depository Services (India) Limited", sector: "Depositories Clearing Houses and Other Intermediaries" },
  { symbol: "CEATLTD", name: "Ceat Limited", sector: "Tyres & Rubber Products" },
  { symbol: "CENTRALBK", name: "Central Bank Of India", sector: "Public Sector Bank" },
  { symbol: "CENTURYPLY", name: "Century Plyboards (India) Limited", sector: "Plywood Boards/ Laminates" },
  { symbol: "CERA", name: "Cera Sanitaryware Limited", sector: "Sanitary Ware" },
  { symbol: "CESC", name: "Cesc Limited", sector: "Integrated Power Utilities" },
  { symbol: "CGCL", name: "Capri Global Capital Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "CGPOWER", name: "Cg Power And Industrial Solutions Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "CHALET", name: "Chalet Hotels Limited", sector: "Hotels & Resorts" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilizers & Chemicals Limited", sector: "Fertilizers" },
  { symbol: "CHENNPETRO", name: "Chennai Petroleum Corporation Limited", sector: "Refineries & Marketing" },
  { symbol: "CHOICEIN", name: "Choice International Limited", sector: "Holding Company" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment And Finance Company Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "CHOLAHLDNG", name: "Cholamandalam Financial Holdings Limited", sector: "Investment Company" },
  { symbol: "CIPLA", name: "Cipla Limited", sector: "Pharmaceuticals" },
  { symbol: "CLEAN", name: "Clean Science And Technology Limited", sector: "Specialty Chemicals" },
  { symbol: "COALINDIA", name: "Coal India Limited", sector: "Coal" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard Limited", sector: "Ship Building & Allied Services" },
  { symbol: "COFORGE", name: "Coforge Limited", sector: "Computers - Software & Consulting" },
  { symbol: "COHANCE", name: "Cohance Lifesciences Limited", sector: "Pharmaceuticals" },
  { symbol: "COLPAL", name: "Colgate Palmolive (India) Limited", sector: "Personal Care" },
  { symbol: "CONCOR", name: "Container Corporation Of India Limited", sector: "Logistics Solution Provider" },
  { symbol: "CONCORDBIO", name: "Concord Biotech Limited", sector: "Pharmaceuticals" },
  { symbol: "COROMANDEL", name: "Coromandel International Limited", sector: "Fertilizers" },
  { symbol: "CRAFTSMAN", name: "Craftsman Automation Limited", sector: "Auto Components & Equipments" },
  { symbol: "CREDITACC", name: "Creditaccess Grameen Limited", sector: "Microfinance Institutions" },
  { symbol: "CRISIL", name: "Crisil Limited", sector: "Other Financial Services" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer Electricals Limited", sector: "Household Appliances" },
  { symbol: "CUB", name: "City Union Bank Limited", sector: "Private Sector Bank" },
  { symbol: "CUMMINSIND", name: "Cummins India Limited", sector: "Compressors Pumps & Diesel Engines" },
  { symbol: "CYIENT", name: "Cyient Limited", sector: "IT Enabled Services" },
  { symbol: "DABUR", name: "Dabur India Limited", sector: "Personal Care" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat Limited", sector: "Cement & Cement Products" },
  { symbol: "DATAPATTNS", name: "Data Patterns (India) Limited", sector: "Aerospace & Defense" },
  { symbol: "DBREALTY", name: "Valor Estate Limited", sector: "Hotels & Resorts" },
  { symbol: "DCMSHRIRAM", name: "Dcm Shriram Limited", sector: "Diversified" },
  { symbol: "DEEPAKFERT", name: "Deepak Fertilizers And Petrochemicals Corporation Limited", sector: "Commodity Chemicals" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite Limited", sector: "Specialty Chemicals" },
  { symbol: "DELHIVERY", name: "Delhivery Limited", sector: "Logistics Solution Provider" },
  { symbol: "DEVYANI", name: "Devyani International Limited", sector: "Restaurants" },
  { symbol: "DIVISLAB", name: "Divi'S Laboratories Limited", sector: "Pharmaceuticals" },
  { symbol: "DIXON", name: "Dixon Technologies (India) Limited", sector: "Consumer Electronics" },
  { symbol: "DLF", name: "Dlf Limited", sector: "Residential Commercial Projects" },
  { symbol: "DMART", name: "Avenue Supermarts Limited", sector: "Diversified Retail" },
  { symbol: "DOMS", name: "Doms Industries Limited", sector: "Stationary" },
  { symbol: "DRREDDY", name: "Dr. Reddy'S Laboratories Limited", sector: "Pharmaceuticals" },
  { symbol: "ECLERX", name: "Eclerx Services Limited", sector: "Business Process Outsourcing (BPO)/ Knowledge Process Outsourcing (KPO)" },
  { symbol: "EICHERMOT", name: "Eicher Motors Limited", sector: "2/3 Wheelers" },
  { symbol: "EIDPARRY", name: "Eid Parry India Limited", sector: "Other Food Products" },
  { symbol: "EIHOTEL", name: "Eih Limited", sector: "Hotels & Resorts" },
  { symbol: "ELECON", name: "Elecon Engineering Company Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "ELGIEQUIP", name: "Elgi Equipments Limited", sector: "Compressors Pumps & Diesel Engines" },
  { symbol: "EMAMILTD", name: "Emami Limited", sector: "Personal Care" },
  { symbol: "EMCURE", name: "Emcure Pharmaceuticals Limited", sector: "Pharmaceuticals" },
  { symbol: "ENDURANCE", name: "Endurance Technologies Limited", sector: "Auto Components & Equipments" },
  { symbol: "ENGINERSIN", name: "Engineers India Limited", sector: "Civil Construction" },
  { symbol: "ENRIN", name: "Siemens Energy India Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "ERIS", name: "Eris Lifesciences Limited", sector: "Pharmaceuticals" },
  { symbol: "ESCORTS", name: "Escorts Kubota Limited", sector: "Tractors" },
  { symbol: "ETERNAL", name: "Eternal Limited", sector: "E-Retail/ E-Commerce" },
  { symbol: "EXIDEIND", name: "Exide Industries Limited", sector: "Auto Components & Equipments" },
  { symbol: "FACT", name: "Fertilizers And Chemicals Travancore Limited", sector: "Fertilizers" },
  { symbol: "FEDERALBNK", name: "The Federal Bank  Limited", sector: "Private Sector Bank" },
  { symbol: "FINCABLES", name: "Finolex Cables Limited", sector: "Cables - Electricals" },
  { symbol: "FINPIPE", name: "Finolex Industries Limited", sector: "Plastic Products - Industrial" },
  { symbol: "FIRSTCRY", name: "Brainbees Solutions Limited", sector: "E-Retail/ E-Commerce" },
  { symbol: "FIVESTAR", name: "Five-Star Business Finance Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "FLUOROCHEM", name: "Gujarat Fluorochemicals Limited", sector: "Specialty Chemicals" },
  { symbol: "FORCEMOT", name: "Force Motors Ltd", sector: "Passenger Cars & Utility Vehicles" },
  { symbol: "FORTIS", name: "Fortis Healthcare Limited", sector: "Hospital" },
  { symbol: "FSL", name: "Firstsource Solutions Limited", sector: "Business Process Outsourcing (BPO)/ Knowledge Process Outsourcing (KPO)" },
  { symbol: "GAIL", name: "Gail (India) Limited", sector: "Gas Transmission/Marketing" },
  { symbol: "GESHIP", name: "The Great Eastern Shipping Company Limited", sector: "Shipping" },
  { symbol: "GICRE", name: "General Insurance Corporation Of India", sector: "General Insurance" },
  { symbol: "GILLETTE", name: "Gillette India Limited", sector: "Personal Care" },
  { symbol: "GLAND", name: "Gland Pharma Limited", sector: "Pharmaceuticals" },
  { symbol: "GLAXO", name: "Glaxosmithkline Pharmaceuticals Limited", sector: "Pharmaceuticals" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals Limited", sector: "Pharmaceuticals" },
  { symbol: "GMDCLTD", name: "Gujarat Mineral Development Corporation Limited", sector: "Industrial Minerals" },
  { symbol: "GMRAIRPORT", name: "Gmr Airports Limited", sector: "Airport & Airport services" },
  { symbol: "GODFRYPHLP", name: "Godfrey Phillips India Limited", sector: "Cigarettes & Tobacco Products" },
  { symbol: "GODIGIT", name: "Go Digit General Insurance Limited", sector: "General Insurance" },
  { symbol: "GODREJAGRO", name: "Godrej Agrovet Limited", sector: "Animal Feed" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products Limited", sector: "Personal Care" },
  { symbol: "GODREJIND", name: "Godrej Industries Limited", sector: "Diversified" },
  { symbol: "GODREJPROP", name: "Godrej Properties Limited", sector: "Residential Commercial Projects" },
  { symbol: "GPIL", name: "Godawari Power And Ispat Limited", sector: "Iron & Steel Products" },
  { symbol: "GRANULES", name: "Granules India Limited", sector: "Pharmaceuticals" },
  { symbol: "GRAPHITE", name: "Graphite India Limited", sector: "Electrodes & Refractories" },
  { symbol: "GRASIM", name: "Grasim Industries Limited", sector: "Cement & Cement Products" },
  { symbol: "GRAVITA", name: "Gravita India Limited", sector: "Industrial Minerals" },
  { symbol: "GRSE", name: "Garden Reach Shipbuilders & Engineers Limited", sector: "Aerospace & Defense" },
  { symbol: "GSPL", name: "Gujarat State Petronet Limited", sector: "Gas Transmission/Marketing" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas Limited", sector: "LPG/CNG/PNG/LNG Supplier" },
  { symbol: "GVT&D", name: "Ge Vernova T&D India Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "HAL", name: "Hindustan Aeronautics Limited", sector: "Aerospace & Defense" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds Technologies Limited", sector: "Computers - Software & Consulting" },
  { symbol: "HAVELLS", name: "Havells India Limited", sector: "Consumer Electronics" },
  { symbol: "HBLENGINE", name: "Hbl Engineering Limited", sector: "Other Industrial Products" },
  { symbol: "HCLTECH", name: "Hcl Technologies Limited", sector: "Computers - Software & Consulting" },
  { symbol: "HDFCAMC", name: "Hdfc Asset Management Company Limited", sector: "Asset Management Company" },
  { symbol: "HDFCBANK", name: "Hdfc Bank Limited", sector: "Private Sector Bank" },
  { symbol: "HDFCLIFE", name: "Hdfc Life Insurance Company Limited", sector: "Life Insurance" },
  { symbol: "HEG", name: "Heg Limited", sector: "Electrodes & Refractories" },
  { symbol: "HEROMOTOCO", name: "Hero Motocorp Limited", sector: "2/3 Wheelers" },
  { symbol: "HEXT", name: "Hexaware Technologies Limited", sector: "Computers - Software & Consulting" },
  { symbol: "HFCL", name: "Hfcl Limited", sector: "Telecom - Infrastructure" },
  { symbol: "HINDALCO", name: "Hindalco Industries Limited", sector: "Aluminium" },
  { symbol: "HINDCOPPER", name: "Hindustan Copper Limited", sector: "Copper" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum Corporation Limited", sector: "Refineries & Marketing" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever Limited", sector: "Diversified FMCG" },
  { symbol: "HINDZINC", name: "Hindustan Zinc Limited", sector: "Zinc" },
  { symbol: "HOMEFIRST", name: "Home First Finance Company India Limited", sector: "Housing Finance Company" },
  { symbol: "HONASA", name: "Honasa Consumer Limited", sector: "Personal Care" },
  { symbol: "HONAUT", name: "Honeywell Automation India Limited", sector: "Industrial Products" },
  { symbol: "HSCL", name: "Himadri Speciality Chemical Limited", sector: "Carbon Black" },
  { symbol: "HUDCO", name: "Housing & Urban Development Corporation Limited", sector: "Financial Institution" },
  { symbol: "HYUNDAI", name: "Hyundai Motor India Limited", sector: "Passenger Cars & Utility Vehicles" },
  { symbol: "ICICIBANK", name: "Icici Bank Limited", sector: "Private Sector Bank" },
  { symbol: "ICICIGI", name: "Icici Lombard General Insurance Company Limited", sector: "General Insurance" },
  { symbol: "ICICIPRULI", name: "Icici Prudential Life Insurance Company Limited", sector: "Life Insurance" },
  { symbol: "IDBI", name: "Idbi Bank Limited", sector: "Private Sector Bank" },
  { symbol: "IDEA", name: "Vodafone Idea Limited", sector: "Telecom - Cellular & Fixed line services" },
  { symbol: "IDFCFIRSTB", name: "Idfc First Bank Limited", sector: "Private Sector Bank" },
  { symbol: "IEX", name: "Indian Energy Exchange Limited", sector: "Exchange and Data Platform" },
  { symbol: "IFCI", name: "Ifci Limited", sector: "Financial Institution" },
  { symbol: "IGIL", name: "International Gemmological Institute (India) Limited", sector: "Diversified Commercial Services" },
  { symbol: "IGL", name: "Indraprastha Gas Limited", sector: "LPG/CNG/PNG/LNG Supplier" },
  { symbol: "IIFL", name: "Iifl Finance Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "IKS", name: "Inventurus Knowledge Solutions Limited", sector: "IT Enabled Services" },
  { symbol: "INDGN", name: "Indegene Limited", sector: "Healthcare Research Analytics & Technology" },
  { symbol: "INDHOTEL", name: "The Indian Hotels Company Limited", sector: "Hotels & Resorts" },
  { symbol: "INDIACEM", name: "The India Cements Limited", sector: "Cement & Cement Products" },
  { symbol: "INDIAMART", name: "Indiamart Intermesh Limited", sector: "Internet & Catalogue Retail" },
  { symbol: "INDIANB", name: "Indian Bank", sector: "Public Sector Bank" },
  { symbol: "INDIGO", name: "Interglobe Aviation Limited", sector: "Airline" },
  { symbol: "INDUSINDBK", name: "Indusind Bank Limited", sector: "Private Sector Bank" },
  { symbol: "INDUSTOWER", name: "Indus Towers Limited", sector: "Telecom - Infrastructure" },
  { symbol: "INFY", name: "Infosys Limited", sector: "Computers - Software & Consulting" },
  { symbol: "INOXINDIA", name: "Inox India Limited", sector: "Other Industrial Products" },
  { symbol: "INOXWIND", name: "Inox Wind Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "INTELLECT", name: "Intellect Design Arena Limited", sector: "Computers - Software & Consulting" },
  { symbol: "IOB", name: "Indian Overseas Bank", sector: "Public Sector Bank" },
  { symbol: "IOC", name: "Indian Oil Corporation Limited", sector: "Refineries & Marketing" },
  { symbol: "IPCALAB", name: "Ipca Laboratories Limited", sector: "Pharmaceuticals" },
  { symbol: "IRB", name: "Irb Infrastructure Developers Limited", sector: "Civil Construction" },
  { symbol: "IRCON", name: "Ircon International Limited", sector: "Civil Construction" },
  { symbol: "IRCTC", name: "Indian Railway Catering And Tourism Corporation Limited", sector: "Tour Travel Related Services" },
  { symbol: "IREDA", name: "Indian Renewable Energy Development Agency Limited", sector: "Financial Institution" },
  { symbol: "IRFC", name: "Indian Railway Finance Corporation Limited", sector: "Financial Institution" },
  { symbol: "ITC", name: "Itc Limited", sector: "Diversified FMCG" },
  { symbol: "ITCHOTELS", name: "Itc Hotels Limited", sector: "Hotels & Resorts" },
  { symbol: "ITI", name: "Iti Limited", sector: "Telecom - Equipment & Accessories" },
  { symbol: "J&KBANK", name: "The Jammu & Kashmir Bank Limited", sector: "Private Sector Bank" },
  { symbol: "JBCHEPHARM", name: "Jb Chemicals & Pharmaceuticals Limited", sector: "Pharmaceuticals" },
  { symbol: "JBMA", name: "Jbm Auto Limited", sector: "Auto Components & Equipments" },
  { symbol: "JINDALSAW", name: "Jindal Saw Limited", sector: "Iron & Steel Products" },
  { symbol: "JINDALSTEL", name: "Jindal Steel Limited", sector: "Iron & Steel" },
  { symbol: "JIOFIN", name: "Jio Financial Services Limited", sector: "Investment Company" },
  { symbol: "JKCEMENT", name: "Jk Cement Limited", sector: "Cement & Cement Products" },
  { symbol: "JKTYRE", name: "Jk Tyre & Industries Limited", sector: "Tyres & Rubber Products" },
  { symbol: "JMFINANCIL", name: "Jm Financial Limited", sector: "Holding Company" },
  { symbol: "JPPOWER", name: "Jaiprakash Power Ventures Limited", sector: "Power Generation" },
  { symbol: "JSL", name: "Jindal Stainless Limited", sector: "Iron & Steel" },
  { symbol: "JSWCEMENT", name: "Jsw Cement Limited", sector: "Cement & Cement Products" },
  { symbol: "JSWENERGY", name: "Jsw Energy Limited", sector: "Power Generation" },
  { symbol: "JSWINFRA", name: "Jsw Infrastructure Limited", sector: "Port & Port services" },
  { symbol: "JSWSTEEL", name: "Jsw Steel Limited", sector: "Iron & Steel" },
  { symbol: "JUBLFOOD", name: "Jubilant Foodworks Limited", sector: "Restaurants" },
  { symbol: "JUBLINGREA", name: "Jubilant Ingrevia Limited", sector: "Specialty Chemicals" },
  { symbol: "JUBLPHARMA", name: "Jubilant Pharmova Limited", sector: "Pharmaceuticals" },
  { symbol: "JWL", name: "Jupiter Wagons Limited", sector: "Railway Wagons" },
  { symbol: "JYOTHYLAB", name: "Jyothy Labs Limited", sector: "Household Products" },
  { symbol: "JYOTICNC", name: "Jyoti Cnc Automation Limited", sector: "Industrial Products" },
  { symbol: "KAJARIACER", name: "Kajaria Ceramics Limited", sector: "Ceramics" },
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers India Limited", sector: "Gems Jewellery And Watches" },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank Limited", sector: "Private Sector Bank" },
  { symbol: "KAYNES", name: "Kaynes Technology India Limited", sector: "Industrial Products" },
  { symbol: "KEC", name: "Kec International Limited", sector: "Civil Construction" },
  { symbol: "KEI", name: "Kei Industries Limited", sector: "Cables - Electricals" },
  { symbol: "KFINTECH", name: "Kfin Technologies Limited", sector: "Depositories Clearing Houses and Other Intermediaries" },
  { symbol: "KIMS", name: "Krishna Institute Of Medical Sciences Limited", sector: "Hospital" },
  { symbol: "KIRLOSBROS", name: "Kirloskar Brothers Limited", sector: "Compressors Pumps & Diesel Engines" },
  { symbol: "KIRLOSENG", name: "Kirloskar Oil Engines Limited", sector: "Compressors Pumps & Diesel Engines" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank Limited", sector: "Private Sector Bank" },
  { symbol: "KPIL", name: "Kalpataru Projects International Limited", sector: "Civil Construction" },
  { symbol: "KPITTECH", name: "Kpit Technologies Limited", sector: "Computers - Software & Consulting" },
  { symbol: "KPRMILL", name: "K.P.R. Mill Limited", sector: "Other Textile Products" },
  { symbol: "KSB", name: "Ksb Limited", sector: "Compressors Pumps & Diesel Engines" },
  { symbol: "LALPATHLAB", name: "Dr. Lal Path Labs Ltd.", sector: "Healthcare Service Provider" },
  { symbol: "LATENTVIEW", name: "Latent View Analytics Limited", sector: "Computers - Software & Consulting" },
  { symbol: "LAURUSLABS", name: "Laurus Labs Limited", sector: "Pharmaceuticals" },
  { symbol: "LEMONTREE", name: "Lemon Tree Hotels Limited", sector: "Hotels & Resorts" },
  { symbol: "LICHSGFIN", name: "Lic Housing Finance Limited", sector: "Housing Finance Company" },
  { symbol: "LICI", name: "Life Insurance Corporation Of India", sector: "Life Insurance" },
  { symbol: "LINDEINDIA", name: "Linde India Limited", sector: "Industrial Gases" },
  { symbol: "LLOYDSME", name: "Lloyds Metals And Energy Limited", sector: "Industrial Minerals" },
  { symbol: "LODHA", name: "Lodha Developers Limited", sector: "Residential Commercial Projects" },
  { symbol: "LT", name: "Larsen & Toubro Limited", sector: "Civil Construction" },
  { symbol: "LTF", name: "L&T Finance Limited", sector: "Investment Company" },
  { symbol: "LTFOODS", name: "Lt Foods Limited", sector: "Other Agricultural Products" },
  { symbol: "LTM", name: "Ltimindtree Limited", sector: "Computers - Software & Consulting" },
  { symbol: "LTTS", name: "L&T Technology Services Limited", sector: "IT Enabled Services" },
  { symbol: "LUPIN", name: "Lupin Limited", sector: "Pharmaceuticals" },
  { symbol: "M&M", name: "Mahindra & Mahindra Limited", sector: "Passenger Cars & Utility Vehicles" },
  { symbol: "M&MFIN", name: "Mahindra & Mahindra Financial Services Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "MAHABANK", name: "Bank Of Maharashtra", sector: "Public Sector Bank" },
  { symbol: "MAHSCOOTER", name: "Maharashtra Scooters Limited", sector: "Investment Company" },
  { symbol: "MAHSEAMLES", name: "Maharashtra Seamless Limited", sector: "Iron & Steel Products" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "MANKIND", name: "Mankind Pharma Limited", sector: "Pharmaceuticals" },
  { symbol: "MANYAVAR", name: "Vedant Fashions Limited", sector: "Speciality Retail" },
  { symbol: "MAPMYINDIA", name: "C.E. Info Systems Limited", sector: "Software Products" },
  { symbol: "MARICO", name: "Marico Limited", sector: "Edible Oil" },
  { symbol: "MARUTI", name: "Maruti Suzuki India Limited", sector: "Passenger Cars & Utility Vehicles" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute Limited", sector: "Hospital" },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders Limited", sector: "Ship Building & Allied Services" },
  { symbol: "MCX", name: "Multi Commodity Exchange Of India Limited", sector: "Exchange and Data Platform" },
  { symbol: "MEDANTA", name: "Global Health Limited", sector: "Hospital" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare Limited", sector: "Healthcare Service Provider" },
  { symbol: "MFSL", name: "Max Financial Services Limited", sector: "Life Insurance" },
  { symbol: "MGL", name: "Mahanagar Gas Limited", sector: "LPG/CNG/PNG/LNG Supplier" },
  { symbol: "MINDACORP", name: "Minda Corporation Limited", sector: "Auto Components & Equipments" },
  { symbol: "MMTC", name: "Mmtc Limited", sector: "Trading & Distributors" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson International Limited", sector: "Auto Components & Equipments" },
  { symbol: "MOTILALOFS", name: "Motilal Oswal Financial Services Limited", sector: "Stockbroking & Allied" },
  { symbol: "MPHASIS", name: "Mphasis Limited", sector: "Computers - Software & Consulting" },
  { symbol: "MRF", name: "Mrf Limited", sector: "Tyres & Rubber Products" },
  { symbol: "MRPL", name: "Mangalore Refinery And Petrochemicals Limited", sector: "Refineries & Marketing" },
  { symbol: "MSUMI", name: "Motherson Sumi Wiring India Limited", sector: "Auto Components & Equipments" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "NAM-INDIA", name: "Nippon Life India Asset Management Limited", sector: "Asset Management Company" },
  { symbol: "NATCOPHARM", name: "Natco Pharma Limited", sector: "Pharmaceuticals" },
  { symbol: "NATIONALUM", name: "National Aluminium Company Limited", sector: "Aluminium" },
  { symbol: "NAUKRI", name: "Info Edge (India) Limited", sector: "Internet & Catalogue Retail" },
  { symbol: "NAVA", name: "Nava Limited", sector: "Power Generation" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine International Limited", sector: "Specialty Chemicals" },
  { symbol: "NBCC", name: "Nbcc (India) Limited", sector: "Civil Construction" },
  { symbol: "NCC", name: "Ncc Limited", sector: "Civil Construction" },
  { symbol: "NESTLEIND", name: "Nestle India Limited", sector: "Packaged Foods" },
  { symbol: "NETWEB", name: "Netweb Technologies India Limited", sector: "IT Enabled Services" },
  { symbol: "NEULANDLAB", name: "Neuland Laboratories Limited", sector: "Pharmaceuticals" },
  { symbol: "NEWGEN", name: "Newgen Software Technologies Limited", sector: "Computers - Software & Consulting" },
  { symbol: "NH", name: "Narayana Hrudayalaya Ltd.", sector: "Hospital" },
  { symbol: "NHPC", name: "Nhpc Limited", sector: "Power Generation" },
  { symbol: "NIACL", name: "The New India Assurance Company Limited", sector: "General Insurance" },
  { symbol: "NIVABUPA", name: "Niva Bupa Health Insurance Company Limited", sector: "General Insurance" },
  { symbol: "NLCINDIA", name: "Nlc India Limited", sector: "Power Generation" },
  { symbol: "NMDC", name: "Nmdc Limited", sector: "Industrial Minerals" },
  { symbol: "NSLNISP", name: "Nmdc Steel Limited", sector: "Iron & Steel" },
  { symbol: "NTPC", name: "Ntpc Limited", sector: "Power Generation" },
  { symbol: "NTPCGREEN", name: "Ntpc Green Energy Limited", sector: "Power Generation" },
  { symbol: "NUVAMA", name: "Nuvama Wealth Management Limited", sector: "Stockbroking & Allied" },
  { symbol: "NUVOCO", name: "Nuvoco Vistas Corporation Limited", sector: "Cement & Cement Products" },
  { symbol: "NYKAA", name: "Fsn E-Commerce Ventures Limited", sector: "E-Retail/ E-Commerce" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty Limited", sector: "Residential Commercial Projects" },
  { symbol: "OFSS", name: "Oracle Financial Services Software Limited", sector: "Software Products" },
  { symbol: "OIL", name: "Oil India Limited", sector: "Oil Exploration & Production" },
  { symbol: "OLAELEC", name: "Ola Electric Mobility Limited", sector: "2/3 Wheelers" },
  { symbol: "OLECTRA", name: "Olectra Greentech Limited", sector: "Passenger Cars & Utility Vehicles" },
  { symbol: "ONESOURCE", name: "Onesource Specialty Pharma Limited", sector: "Pharmaceuticals" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation Limited", sector: "Oil Exploration & Production" },
  { symbol: "PAGEIND", name: "Page Industries Limited", sector: "Garments & Apparels" },
  { symbol: "PATANJALI", name: "Patanjali Foods Limited", sector: "Edible Oil" },
  { symbol: "PAYTM", name: "One 97 Communications Limited", sector: "Financial Technology (Fintech)" },
  { symbol: "PCBL", name: "Pcbl Chemical Limited", sector: "Carbon Black" },
  { symbol: "PERSISTENT", name: "Persistent Systems Limited", sector: "Computers - Software & Consulting" },
  { symbol: "PETRONET", name: "Petronet Lng Limited", sector: "LPG/CNG/PNG/LNG Supplier" },
  { symbol: "PFC", name: "Power Finance Corporation Limited", sector: "Financial Institution" },
  { symbol: "PFIZER", name: "Pfizer Limited", sector: "Pharmaceuticals" },
  { symbol: "PGEL", name: "Pg Electroplast Limited", sector: "Consumer Electronics" },
  { symbol: "PGHH", name: "Procter & Gamble Hygiene And Health Care Limited", sector: "Personal Care" },
  { symbol: "PHOENIXLTD", name: "The Phoenix Mills Limited", sector: "Residential Commercial Projects" },
  { symbol: "PIDILITIND", name: "Pidilite Industries Limited", sector: "Specialty Chemicals" },
  { symbol: "PIIND", name: "Pi Industries Limited", sector: "Pesticides & Agrochemicals" },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Public Sector Bank" },
  { symbol: "PNBHOUSING", name: "Pnb Housing Finance Limited", sector: "Housing Finance Company" },
  { symbol: "POLICYBZR", name: "Pb Fintech Limited", sector: "Financial Technology (Fintech)" },
  { symbol: "POLYCAB", name: "Polycab India Limited", sector: "Cables - Electricals" },
  { symbol: "POLYMED", name: "Poly Medicure Limited", sector: "Medical Equipment & Supplies" },
  { symbol: "POONAWALLA", name: "Poonawalla Fincorp Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "POWERGRID", name: "Power Grid Corporation Of India Limited", sector: "Power - Transmission" },
  { symbol: "POWERINDIA", name: "Hitachi Energy India Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "PPLPHARMA", name: "Piramal Pharma Limited", sector: "Pharmaceuticals" },
  { symbol: "PRAJIND", name: "Praj Industries Limited", sector: "Industrial Products" },
  { symbol: "PREMIERENE", name: "Premier Energies Limited", sector: "Other Electrical Equipment" },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects Limited", sector: "Residential Commercial Projects" },
  { symbol: "PTCIL", name: "Ptc Industries Limited", sector: "Other Industrial Products" },
  { symbol: "PVRINOX", name: "Pvr Inox Limited", sector: "Film Production Distribution & Exhibition" },
  { symbol: "RADICO", name: "Radico Khaitan Limited", sector: "Breweries & Distilleries" },
  { symbol: "RAILTEL", name: "Railtel Corporation Of India Limited", sector: "Other Telecom Services" },
  { symbol: "RAINBOW", name: "Rainbow Childrens Medicare Limited", sector: "Hospital" },
  { symbol: "RAMCOCEM", name: "The Ramco Cements Limited", sector: "Cement & Cement Products" },
  { symbol: "RBLBANK", name: "Rbl Bank Limited", sector: "Private Sector Bank" },
  { symbol: "RCF", name: "Rashtriya Chemicals And Fertilizers Limited", sector: "Fertilizers" },
  { symbol: "RECLTD", name: "Rec Limited", sector: "Financial Institution" },
  { symbol: "REDINGTON", name: "Redington Limited", sector: "Trading & Distributors" },
  { symbol: "RELIANCE", name: "Reliance Industries Limited", sector: "Refineries & Marketing" },
  { symbol: "RELINFRA", name: "Reliance Infrastructure Limited", sector: "Integrated Power Utilities" },
  { symbol: "RHIM", name: "Rhi Magnesita India Limited", sector: "Electrodes & Refractories" },
  { symbol: "RITES", name: "Rites Limited", sector: "Civil Construction" },
  { symbol: "RKFORGE", name: "Ramkrishna Forgings Limited", sector: "Auto Components & Equipments" },
  { symbol: "RPOWER", name: "Reliance Power Limited", sector: "Power Generation" },
  { symbol: "RRKABEL", name: "R R Kabel Limited", sector: "Cables - Electricals" },
  { symbol: "RVNL", name: "Rail Vikas Nigam Limited", sector: "Civil Construction" },
  { symbol: "SAGILITY", name: "Sagility Limited", sector: "IT Enabled Services" },
  { symbol: "SAIL", name: "Steel Authority Of India Limited", sector: "Iron & Steel" },
  { symbol: "SAILIFE", name: "Sai Life Sciences Limited", sector: "Pharmaceuticals" },
  { symbol: "SAMMAANCAP", name: "Sammaan Capital Limited", sector: "Housing Finance Company" },
  { symbol: "SAPPHIRE", name: "Sapphire Foods India Limited", sector: "Restaurants" },
  { symbol: "SARDAEN", name: "Sarda Energy & Minerals Limited", sector: "Iron & Steel" },
  { symbol: "SAREGAMA", name: "Saregama India Limited", sector: "Media & Entertainment" },
  { symbol: "SBFC", name: "Sbfc Finance Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "SBICARD", name: "Sbi Cards And Payment Services Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "SBILIFE", name: "Sbi Life Insurance Company Limited", sector: "Life Insurance" },
  { symbol: "SBIN", name: "State Bank Of India", sector: "Public Sector Bank" },
  { symbol: "SCHAEFFLER", name: "Schaeffler India Limited", sector: "Auto Components & Equipments" },
  { symbol: "SCHNEIDER", name: "Schneider Electric Infrastructure Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "SCI", name: "Shipping Corporation Of India Limited", sector: "Shipping" },
  { symbol: "SHREECEM", name: "Shree Cement Limited", sector: "Cement & Cement Products" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "SHYAMMETL", name: "Shyam Metalics And Energy Limited", sector: "Iron & Steel Products" },
  { symbol: "SIEMENS", name: "Siemens Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "SIGNATURE", name: "Signatureglobal (India) Limited", sector: "Residential Commercial Projects" },
  { symbol: "SJVN", name: "Sjvn Limited", sector: "Power Generation" },
  { symbol: "SOBHA", name: "Sobha Limited", sector: "Residential Commercial Projects" },
  { symbol: "SOLARINDS", name: "Solar Industries India Limited", sector: "Explosives" },
  { symbol: "SONACOMS", name: "Sona Blw Precision Forgings Limited", sector: "Auto Components & Equipments" },
  { symbol: "SONATSOFTW", name: "Sonata Software Limited", sector: "Computers - Software & Consulting" },
  { symbol: "SRF", name: "Srf Limited", sector: "Specialty Chemicals" },
  { symbol: "STARHEALTH", name: "Star Health And Allied Insurance Company Limited", sector: "General Insurance" },
  { symbol: "SUMICHEM", name: "Sumitomo Chemical India Limited", sector: "Pesticides & Agrochemicals" },
  { symbol: "SUNDARMFIN", name: "Sundaram Finance Limited", sector: "Non Banking Financial Company (NBFC)" },
  { symbol: "SUNDRMFAST", name: "Sundram Fasteners Limited", sector: "Auto Components & Equipments" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries Limited", sector: "Pharmaceuticals" },
  { symbol: "SUNTV", name: "Sun Tv Network Limited", sector: "TV Broadcasting & Software Production" },
  { symbol: "SUPREMEIND", name: "Supreme Industries Limited", sector: "Plastic Products - Industrial" },
  { symbol: "SUZLON", name: "Suzlon Energy Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "SWANCORP", name: "Swan Corp Limited", sector: "Petrochemicals" },
  { symbol: "SWIGGY", name: "Swiggy Limited", sector: "E-Retail/ E-Commerce" },
  { symbol: "SYNGENE", name: "Syngene International Limited", sector: "Healthcare Research Analytics & Technology" },
  { symbol: "SYRMA", name: "Syrma Sgs Technology Limited", sector: "Industrial Products" },
  { symbol: "TARIL", name: "Transformers And Rectifiers (India) Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "TATACHEM", name: "Tata Chemicals Limited", sector: "Commodity Chemicals" },
  { symbol: "TATACOMM", name: "Tata Communications Limited", sector: "Telecom - Cellular & Fixed line services" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Limited", sector: "Tea & Coffee" },
  { symbol: "TATAELXSI", name: "Tata Elxsi Limited", sector: "Computers - Software & Consulting" },
  { symbol: "TATAINVEST", name: "Tata Investment Corporation Limited", sector: "Investment Company" },
  { symbol: "TATAPOWER", name: "Tata Power Company Limited", sector: "Integrated Power Utilities" },
  { symbol: "TATASTEEL", name: "Tata Steel Limited", sector: "Iron & Steel" },
  { symbol: "TATATECH", name: "Tata Technologies Limited", sector: "IT Enabled Services" },
  { symbol: "TBOTEK", name: "Tbo Tek Limited", sector: "Tour Travel Related Services" },
  { symbol: "TCS", name: "Tata Consultancy Services Limited", sector: "Computers - Software & Consulting" },
  { symbol: "TECHM", name: "Tech Mahindra Limited", sector: "Computers - Software & Consulting" },
  { symbol: "TECHNOE", name: "Techno Electric & Engineering Company Limited", sector: "Civil Construction" },
  { symbol: "TEJASNET", name: "Tejas Networks Limited", sector: "Telecom - Equipment & Accessories" },
  { symbol: "THELEELA", name: "Leela Palaces Hotels & Resorts Limited", sector: "Hotels & Resorts" },
  { symbol: "THERMAX", name: "Thermax Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "TIINDIA", name: "Tube Investments Of India Limited", sector: "Auto Components & Equipments" },
  { symbol: "TIMKEN", name: "Timken India Limited", sector: "Abrasives & Bearings" },
  { symbol: "TITAGARH", name: "Titagarh Rail Systems Limited", sector: "Railway Wagons" },
  { symbol: "TITAN", name: "Titan Company Limited", sector: "Gems Jewellery And Watches" },
  { symbol: "TMPV", name: "Tata Motors Passenger Vehicles Limited", sector: "Passenger Cars & Utility Vehicles" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals Limited", sector: "Pharmaceuticals" },
  { symbol: "TORNTPOWER", name: "Torrent Power Limited", sector: "Integrated Power Utilities" },
  { symbol: "TRENT", name: "Trent Limited", sector: "Speciality Retail" },
  { symbol: "TRIDENT", name: "Trident Limited", sector: "Other Textile Products" },
  { symbol: "TRITURBINE", name: "Triveni Turbine Limited", sector: "Heavy Electrical Equipment" },
  { symbol: "TRIVENI", name: "Triveni Engineering & Industries Limited", sector: "Sugar" },
  { symbol: "TTML", name: "Tata Teleservices (Maharashtra) Limited", sector: "Telecom - Cellular & Fixed line services" },
  { symbol: "TVSMOTOR", name: "Tvs Motor Company Limited", sector: "2/3 Wheelers" },
  { symbol: "UBL", name: "United Breweries Limited", sector: "Breweries & Distilleries" },
  { symbol: "UCOBANK", name: "Uco Bank", sector: "Public Sector Bank" },
  { symbol: "ULTRACEMCO", name: "Ultratech Cement Limited", sector: "Cement & Cement Products" },
  { symbol: "UNIONBANK", name: "Union Bank Of India", sector: "Public Sector Bank" },
  { symbol: "UNITDSPR", name: "United Spirits Limited", sector: "Breweries & Distilleries" },
  { symbol: "UNOMINDA", name: "Uno Minda Limited", sector: "Auto Components & Equipments" },
  { symbol: "UPL", name: "Upl Limited", sector: "Pesticides & Agrochemicals" },
  { symbol: "USHAMART", name: "Usha Martin Limited", sector: "Iron & Steel Products" },
  { symbol: "UTIAMC", name: "Uti Asset Management Company Limited", sector: "Asset Management Company" },
  { symbol: "VBL", name: "Varun Beverages Limited", sector: "Other Beverages" },
  { symbol: "VEDL", name: "Vedanta Limited", sector: "Diversified Metals" },
  { symbol: "VENTIVE", name: "Ventive Hospitality Limited", sector: "Hotels & Resorts" },
  { symbol: "VGUARD", name: "V-Guard Industries Limited", sector: "Household Appliances" },
  { symbol: "VIJAYA", name: "Vijaya Diagnostic Centre Limited", sector: "Healthcare Service Provider" },
  { symbol: "VMM", name: "Vishal Mega Mart Limited", sector: "Diversified Retail" },
  { symbol: "VOLTAS", name: "Voltas Limited", sector: "Household Appliances" },
  { symbol: "VTL", name: "Vardhman Textiles Limited", sector: "Other Textile Products" },
  { symbol: "WAAREEENER", name: "Waaree Energies Limited", sector: "Other Electrical Equipment" },
  { symbol: "WELCORP", name: "Welspun Corp Limited", sector: "Iron & Steel Products" },
  { symbol: "WELSPUNLIV", name: "Welspun Living Limited", sector: "Other Textile Products" },
  { symbol: "WHIRLPOOL", name: "Whirlpool Of India Limited", sector: "Household Appliances" },
  { symbol: "WIPRO", name: "Wipro Limited", sector: "Computers - Software & Consulting" },
  { symbol: "WOCKPHARMA", name: "Wockhardt Limited", sector: "Pharmaceuticals" },
  { symbol: "YESBANK", name: "Yes Bank Limited", sector: "Private Sector Bank" },
  { symbol: "ZEEL", name: "Zee Entertainment Enterprises Limited", sector: "TV Broadcasting & Software Production" },
  { symbol: "ZENSARTECH", name: "Zensar Technologies Limited", sector: "Computers - Software & Consulting" },
  { symbol: "ZENTEC", name: "Zen Technologies Limited", sector: "Aerospace & Defense" },
  { symbol: "ZFCVINDIA", name: "Zf Commercial Vehicle Control Systems India Limited", sector: "Auto Components & Equipments" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences Limited", sector: "Pharmaceuticals" },
];

// Starts with all NIFTY 500; API results merge in later
let _stockCache: NseStock[] = [...NIFTY_500];

export function setStockCache(stocks: NseStock[]) {
  const existing = new Set(_stockCache.map((s) => s.symbol));
  const newStocks = stocks.filter((s) => !existing.has(s.symbol));
  _stockCache = [..._stockCache, ...newStocks];
}

export function searchLocalStocks(query: string, limit = 10): NseStock[] {
  if (!query || query.length < 1) return [];
  const q = query.toUpperCase();

  // Prioritize: exact symbol prefix > symbol contains > name contains
  const exactPrefix: NseStock[] = [];
  const symbolContains: NseStock[] = [];
  const nameContains: NseStock[] = [];

  for (const s of _stockCache) {
    const sym = s.symbol.toUpperCase();
    const name = s.name.toUpperCase();
    if (sym.startsWith(q)) {
      exactPrefix.push(s);
    } else if (sym.includes(q)) {
      symbolContains.push(s);
    } else if (name.includes(q)) {
      nameContains.push(s);
    }
  }

  return [...exactPrefix, ...symbolContains, ...nameContains].slice(0, limit);
}

const _sectorBySymbol = new Map(NIFTY_500.map((s) => [s.symbol, s.sector]));

/** Sector from the bundled NIFTY 500 list, for API rows that arrive without one. */
export function sectorFor(symbol: string): string {
  return _sectorBySymbol.get(symbol) ?? "";
}
